In [1]:
from AOC_utils import get_day
import numpy as np
from numpy import lib

day = 22
input_data = get_day(day)

# print out first few lines to get a feel for the data
print(len(input_data))
input_data[:7]

Day 22 input already downloaded
2044


['7798933', '14182798', '2317489', '2761480', '12070436', '6811285', '9207844']

In [2]:
example = '''
1
2
3
2024
'''.split('\n')[1:-1]

In [7]:
import time

In [14]:
def solve_day(data):
    part1 = 0
    part2 = 0

    data = np.array([int(x) for x in data], dtype=np.int64)

    def secret_iter(data, n=2000):
        all_numbers = np.zeros((n+1, len(data)))
        all_numbers[0] = data
        for i in range(n):
            nd = data * 64
            data = (nd ^ data) % 16777216
            nd = data // 32
            data = (nd ^ data) % 16777216
            nd = data * 2048
            data = (nd ^ data) % 16777216
            all_numbers[i+1] = data
        return data, all_numbers

    data, all_numbers = secret_iter(data)

    part1 = np.sum(data)

    prices = all_numbers % 10
    price_changes = np.diff(prices, axis=0)

    price_change_windows = lib.stride_tricks.sliding_window_view(price_changes, 4, axis=0)
    sliced_prices = prices[4:]

    print(price_change_windows.shape)
    print(sliced_prices.shape)
    
    best_window = -1

    sequences = np.unique(price_change_windows.reshape(-1, 4), axis=-1)
    for window in sequences:
        where_window = np.all(window == price_change_windows, axis=-1)
        if not np.any(where_window):
            continue

        first_occurances = []
        occurance_dims = []
        for dim in range(where_window.shape[-1]):
            occurances = np.arange(len(price_change_windows))[where_window[:,dim]]
            if len(occurances) > 0:
                first_occurances.append(occurances[0])
                occurance_dims.append(dim)

        if first_occurances:
            total_price = np.sum([sliced_prices[i, j] for i, j in zip(first_occurances, occurance_dims)])
            if total_price > best_window:
                best_window = total_price

    part2 = best_window

    print("part 1:", part1)
    print("part 2:", part2)

solve_day(example)

(1997, 4, 4)
(1997, 4)
part 1: 37990510
part 2: 21.0


In [ ]:
solve_day(input_data)

(1997, 2044, 4)
(1997, 2044)
[ 6. -3. -3. -3.] 0.0
[-8.  4. -1. -3.] 42.0
[-3. -3. -2.  8.] 659.0
[ 2. -2. -4.  6.] 1121.0
[-3.  3. -2.  5.] 1278.0
[-5.  5. -1.  1.] 1343.0
[ 3.  1. -2.  1.] 1382.0
[ 1. -4.  0.  5.] 1430.0
[0. 0. 4. 0.] 1464.0
[ 0. -1. -2.  3.] 1612.0
[ 0. -4.  1.  3.] 1636.0
[-1.  2.  0.  0.] 1766.0
[-2.  0. -1.  3.] 1767.0
[-1.  1. -1.  2.] 1901.0
[ 1. -1.  0.  1.] 1910.0
